apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyterlab-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jupyterlab-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: jupyterlab-app
    spec:
      containers:
      - name: jupyterlab-app
        image: sekharbuddha/testkube:jupyterserver
        ports:
        - containerPort: 8888  # Expose the correct port for JupyterLab
        env:
        - name: JUPYTER_TOKEN
          value: "sekhar"  # Static token to avoid dynamic generation

---
apiVersion: v1
kind: Service
metadata:
  name: jupyterlab-service
  namespace: default
spec:
  selector:
    app: jupyterlab-app
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
      nodePort: 30088
  type: NodePort  # Use NodePort if you're on Minikube or Docker Desktop
