apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-app
spec:
  replicas: 2  # Number of replicas to test load balancing
  spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1  # Number of pods that can be unavailable during the update
      maxSurge: 1  
  selector:
    matchLabels:
      app: streamlit-app
  template:
    metadata:
      labels:
        app: streamlit-app
    spec:
      containers:
      - name: streamlit-app
        image: sekharbuddha/test-kube:v2  # Replace with your image
        ports:
        - containerPort: 8501

---
apiVersion: v1
kind: Service
metadata:
  name: streamlit-service
spec:
  selector:
    app: streamlit-app
  ports:
  - protocol: TCP
    port: 80             # Service port
    targetPort: 8501      # The port your Streamlit app is running on in the container
    nodePort: 30007       # A NodePort in the range 30000–32767 (can be any valid port)
  type: NodePort
