apiVersion: v1
kind: PersistentVolume
metadata:
  name: jupyterlab-pv
  namespace: default
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: '/Users/sekhar/Documents/mount_k8s'  # Path to the folder on your Mac
